### ISSUE TITLE
hsreplay 연동 관련

### ISSUE THREAD

**Issue by icepeng** [Yeoto/Hearthstone_Deck_Maker#1]
[http://icepeng.com/home](http://icepeng.com/home)

이런걸 만들었던 사람입니다.

하스스톤 관련 프로그램을 제작하신다기에 도움을 드리고 싶습니다.

기본적으로, 오픈소스 프로젝트면 hsreplay측에서 데이터 이용하는건 문제삼지 않습니다. 메일 한번 보내서 부탁하실때 리포 링크도 같이 보내시면 될겁니다.

[https://discordapp.com/invite/hearthsim-devs](https://discordapp.com/invite/hearthsim-devs)

hsreplay 관련 개발자 디스코드도 있으니 참가하시면 프로그램 홍보에도 도움이 될겁니다.

직업별 메타 덱 불러오기를 구현하기 위해서는

[https://hsreplay.net/api/v1/archetypes/](https://hsreplay.net/api/v1/archetypes/
)
[https://hsreplay.net/analytics/query/list_decks_by_win_rate/?GameType=RANKED_STANDARD&RankRange=LEGEND_THROUGH_TWENTY&TimeRange=LAST_30_DAYS](https://hsreplay.net/analytics/query/list_decks_by_win_rate/?GameType=RANKED_STANDARD&RankRange=LEGEND_THROUGH_TWENTY&TimeRange=LAST_30_DAYS)

두개의 엔드포인트를 이용해야 합니다.

`/archetypes` 에서 모든 아키타입의 id와 이름을 가져온 다음

`/list_decks_by_winrate` 에서 가져온 데이터를 보면

```
{
  "render_as": "table",
  "series": {
    "metadata": {
      "DRUID": {},
      "HUNTER": {},
      "MAGE": {},
      "PALADIN": {},
      "PRIEST": {},
      "ROGUE": {},
      "SHAMAN": {},
      "WARLOCK": {},
      "WARRIOR": {}
    },
    "data": {
      "DRUID": [
        {
          "deck_id": "A0wK7YR5oPb4CuNNaiDLOg",
          "deck_list": "[[49164,1],[51779,2],[381,2],[48607,2],[52810,2],[47063,2],[503,2],[757,2],[52438,1],[52819,2],[51781,2],[64,2],[51380,2],[51790,2],[742,2],[50042,2]]",
          "archetype_id": 7,
          "digest": "daa8cd35111a29431b2a21e54ea15d9a",
          "total_games": 1003,
          "win_rate": 59.52,
          "avg_game_length_seconds": 407.0,
          "avg_num_player_turns": 8.0
        },
        {
          "deck_id": "Xlx24vactV55bhR3jWRw6b",
          "deck_list": "[[49164,2],[50356,1],[51779,2],[381,2],[52809,1],[48607,2],[52810,2],[47063,2],[503,2],[43310,1],[52438,1],[493,1],[52819,2],[64,2],[51790,2],[49621,2],[52487,1],[742,2]]",
          "archetype_id": 7,
          "digest": "3fc9ba19d10527ee030fccb8f4308167",
          "total_games": 1022,
          "win_rate": 59.29,
          "avg_game_length_seconds": 413.0,
          "avg_num_player_turns": 8.0
        },

//이하 생략
```

이렇게 되어있는데, 여기서 archetype_id를 통해 이전에 가져온 정보와 매칭을 할 수 있습니다.

각 `archetype_id`에 대해 그룹을 만든 다음, 그룹 내에서 `total_games`와 `win_rate`을 적당히 고려해 상위 n개의 덱을 추려내면 됩니다.

프리미엄 유저라면 `/list_decks_by_winrate` 에 붙는 쿼리를 바꿔서 전설 구간 승률 등도 조회가 가능하지만, 대부분은 아닐테니 그대로 하면 될것 같습니다.

도움이 되었으면 좋겠습니다. 좋은 프로그램으로 거듭났으면 합니다.

**Comment by Yeoto** [comment]
헐 오리엔탈 샐러드 개발자님..
충성충성^^7 열심히 할게오

**Comment by solarias** [comment]
심플스톤 개발자 입니다. 지나가는 길에 좋은 가르침 받고 갑니다.
